### ISSUE TITLE
zepto

### ISSUE THREAD

**Issue by walterDurin** [civicsource/knockout.spin#3]
Neither knockout or spin require jQuery, but your spin wrapper adds a jQuery dependency, can you not use jQuery or zepto based on what is available or use standard javascript?

**Comment by mdarens** [comment]
Sounds like a great idea!

It looks like we're only using jQuery for:
* `Deferred.promise`
* `extend`ing options
* the `css` method
* `show` and `hide`

We'd be happy to accept a PR.
